version: '3.8'
 
services:
  flask-app:
    container_name: flask-app
    image: flask-app:1.0
    environment:
      MYSQL_DATABASE: enameli
      MYSQL_USER: enna
      MYSQL_PASSWORD: poiuytre
    ports:
      - "5002:5000"
    networks:
      - app-net
 
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    ports:
      - "3306:3306"  # Corrected the port mapping here
    environment:
      MYSQL_ROOT_PASSWORD: iddirena
      MYSQL_DATABASE: enameli
      MYSQL_USER: enna
      MYSQL_PASSWORD: poiuytre
    networks:
      - app-net

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    links:
      - mysqldb:db
    ports:
      - "8080:80"
    networks:
      - app-net


networks:
  app-net:
    name: app-net