apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp-deployment
  labels:
    app: flaskapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
        - name: flask-app
          image: flask-app:1.1
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysqldb-secret
                  key: mysql-root-password
            - name: MYSQL_USER
              valueFrom: 
                secretKeyRef:
                  name: mysqldb-secret
                  key: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: mysqldb-secret
                  key: mysql-password
            - name: MYSQL_DATABASE
              value: enameli
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: flaskapp

